DROP TABLE IF EXISTS TML_CONF;
CREATE TABLE TML_CONF(
	id INT,
	groupName VARCHAR(128),
	portalUrl VARCHAR(128),
	logServerUrl VARCHAR(128),
	ntpServerUrl VARCHAR(128),
	PRIMARY KEY(id)
) DEFAULT CHARACTER SET UTF8;

