CREATE TABLE SYS_USER(
	USERID INTEGER,
	TYPE INTEGER DEFAULT 0,	
	NAME VARCHAR(255),
	PWD VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(255),
	MOBILE VARCHAR(255),
	PRIMARY KEY(USERID)
);

CREATE TABLE SYS_HISTORY(
	HISTORYID INTEGER,
	HISTIME TIMESTAMP,
	USERID INTEGER DEFAULT 0,
	USERNAME VARCHAR(200),
	LOGTYPE INTEGER DEFAULT 0,
	CLIENTIP VARCHAR(64),
	PRIMARY KEY(HISTORYID)
);

CREATE TABLE SYS_ROLE(
	ROLEID INTEGER,
	NAME VARCHAR(255),
	VALUE VARCHAR(255),
	PARENT VARCHAR(255),
	PRIORITY INTEGER DEFAULT 0,
	PRIMARY KEY (ROLEID)
);

CREATE TABLE SYS_USER_ROLE(
	USERID INTEGER,
	ROLEID INTEGER
);

CREATE TABLE SYS_DOM(
	DOMID           INTEGER,
	DONAME			VARCHAR(50) NOT NULL,
	PARENTID		INTEGER DEFAULT -1,
	PARENTNAME		VARCHAR(50),
	TYPE 			INTEGER DEFAULT 0,
	DDESC			VARCHAR(50),
	CREATE_TIME 	TIMESTAMP,
	CREATOR        	VARCHAR(50),
	PRIMARY KEY (DOMID)
);

CREATE TABLE SYS_USER_DOM(
	USERID INTEGER,
	DOMID INTEGER
);

CREATE TABLE SYS_CONFIGURE(
	ID INTEGER,
	NAME VARCHAR(255),
	VALUE VARCHAR(255),
	DDESC VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE SYS_LOG(
	ID INTEGER,
	WWHO VARCHAR(255),
	TTIME TIMESTAMP,
	DDESC VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE SYS_LOG_SEQ(
	NNEXT INTEGER DEFAULT 1,
	PRIMARY KEY (NNEXT)
);

